name: 'Terraform CD'

on:
  push:
    branches: [ "main" ]

# Definimos variables globales para este flujo
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  BUCKET_NAME: "cv-project-dpr-30122025" # <--- Cambia esto aquí fácilmente
  REGION: "us-central1"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      # Aquí usamos las variables definidas arriba con 'env.'
      run: |
        terraform apply \
          -var="project_id=${{ env.PROJECT_ID }}" \
          -var="bucket_name=${{ env.BUCKET_NAME }}" \
          -var="region=${{ env.REGION }}" \
          -auto-approve